package main

import (
	"fmt"

	. "github.com/dave/jennifer/jen"
)

func main() {
	// code generate part
	f := NewFile("validator_examples")

	// Header comments
	f.HeaderComment("Code generated by protoc-gen-gogo. DO NOT EDIT.")
	f.HeaderComment("source: examples/enum.proto")

	// generator
	f = genValidatorFunc(f)

	// code print part
	fmt.Printf("%#v", f)
}

func genValidatorFunc(f *File) *File {
	f.Func().Params(Id("this").Id("*InnerMessage")).Id("Validator").Params().Error().Block(
		If(Op("!").Parens(Id("this").Dot("SomeInteger"))).Block(
			Return(Qual("fmt", "Errorf").Call(Lit("value '%v' must be less than '100'"))),
		),
	)

	return f
}
